### ISSUE TITLE
How to take a snapshot?

### ISSUE THREAD

**Issue by mvmcjr** [cheatdeath/Sof.Vlc.Http#1]
First of all congratulations on your great work, it help me out a lot, but I've been struggling to take a screen snapshot I know the method exists, but I've not seen where to get it.

**Comment by seanoflynn** [comment]
Thanks a lot. [VlcClient.TakeSnapshot()](https://github.com/seanoflynn/Sof.Vlc.Http/blob/master/src/Sof.Vlc.Http/VlcClient.cs#L211) will take a snapshot and save it in your user pictures/photos folder e.g. depending on the OS, it's something like /Users/john/Pictures/vlcsnap-2017-09-04-21h08m49s037.png. You can change the location, prefix and format in VLC settings/preferences under video (see the [official documentation](https://wiki.videolan.org/Documentation:Snapshots/)).
