### ISSUE TITLE
Volume Bug

### ISSUE THREAD

**Issue by mvmcjr** [cheatdeath/Sof.Vlc.Http#3]
This bug may not be related to the project but VLC itself, but I can't seem to set the volume based on percentage.

`
http://127.0.0.1:8080/requests/playlist.xml?command=volume&val=50%
`

Or

`http://127.0.0.1:8080/requests/playlist.xml?command=volume&val=50%25`

Returns

`.../package/win32/../../../share/lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)`

**Comment by seanoflynn** [comment]
Yeah it doesn't look like VLC supports percentage volumes. It is mentioned in their [documentation](https://wiki.videolan.org/VLC_HTTP_requests/) but doesn't seem to be implemented in the [lua code](https://github.com/videolan/vlc/blob/master/share/lua/modules/common.lua#L171) on the other side. You can see the check for a percentage sign in the seek method above but not in the volume method.

**Comment by mvmcjr** [comment]
That's strange from VideoLan, anyways thanks, [I did a workaround on my fork](https://github.com/seanoflynn/Sof.Vlc.Http/pull/2) !
